#!/usr/bin/env python
# coding=utf-8

import sys

import virtualizer

try:
    xml = sys.stdin.read()
    v = virtualizer.Virtualizer.parse_from_text(xml)
except:
    sys.stderr.write("Error parsing XML from stdin\n")
else:
    print v
